version: "3.9"
services: 

    postgresql:
        image: postgres:alpine
        restart: always
        ports:
            - 5432:5432
        volumes:
            - docker-compose_psqldata:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: huggi678213

volumes:
    docker-compose_psqldata:
        external: true