version: "3.9"
services: 
    fakeprod:
        image: jimfakeproducer:latest
        build: ./customDocker/fakeproducer
        restart: on-failure
        environment: 
            PORT: 6023
            
    rabbitmq:
        image: rabbitmq:alpine
        restart: always

    ingestor:
        image: jimingestor:latest
        build: ./customDocker/ingestor
        depends_on: 
            - fakeprod
            - rabbitmq
        restart: on-failure
        environment: 
            TELNETSERVER: fakeprod
            TELNETPORT: 6023
            RABBITMQHOST: rabbitmq

    postgresql:
        image: postgres:alpine
        restart: always
        ports:
            - 5432:5432
        volumes:
            - psqldata:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: huggi678213

    blockifier:
        image: jimblockifier:latest
        build: ./customDocker/blockifier
        depends_on: 
            - rabbitmq
            - ingestor
        restart: on-failure
        environment: 
            RABBITMQHOST: rabbitmq
    
    pandas2sql:
        image: jimpandas2sql:latest
        build: ./customDocker/df2sql
        depends_on: 
            - rabbitmq
            - blockifier
            - postgresql
        restart: on-failure
        environment: 
            RABBITMQHOST: rabbitmq
            POSTGRES_HOST: postgresql
            POSTGRES_PASSWORD: huggi678213 

volumes:
    psqldata: