version: "3.9"
services: 
    # fakeprod:
    #     image: guestros/telnet-tickdata-fakeproducer:latest
    #     build: ./customDocker/fakeproducer
    #     restart: "no" # # bc if done just fuck off 
    #     environment: 
    #         PORT: 6023
            
    rabbitmq:
        image: rabbitmq:alpine
        restart: always

    ingestor:
        image: guestros/telnet-tickdata-ingestor:latest
        build: ./customDocker/ingestor
        depends_on: 
            - rabbitmq
        restart: always 
        environment: 
            TELNETSERVER: "203.24.211.20"
            TELNETPORT: 41000  # 6023
            RABBITMQHOST: rabbitmq

    postgresql:
        image: postgres:alpine
        restart: always
        ports:
            - 5432:5432
        volumes:
            - psqldata:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: huggi678213

    blockifier:
        image: guestros/jim-tickdata-blockifier:latest
        build: ./customDocker/blockifier
        depends_on: 
            - rabbitmq
            - ingestor
        restart: on-failure
        environment: 
            RABBITMQHOST: rabbitmq
            POSTGRES_HOST: postgresql
            POSTGRES_PASSWORD: huggi678213 
    
    pandas2sql:
        image: guestros/jim-tickdata-pandas2sql:latest
        build: ./customDocker/df2sql
        depends_on: 
            - rabbitmq
            - blockifier
            - postgresql
        restart: on-failure
        environment: 
            RABBITMQHOST: rabbitmq
            POSTGRES_HOST: postgresql
            POSTGRES_PASSWORD: huggi678213 

    simplesuperset:
        image: guestros/apache-superset-simple:latest
        depends_on: 
            - postgresql
        restart: always
        ports:
            - 80:8088
        volumes:
            - superset:/root/.superset/


volumes:
    psqldata:
    superset: